### ISSUE TITLE
Remove sparse_mode kwarg not present in fvgp

### ISSUE THREAD

**Issue by ronpandolfi** [lbl-camera/gpCAM#33]
The `sparse_mode` kwarg is no longer present in `fvgp/gp.py:GP.__init__`. If this is no longer an available option, remove it from `gpcam/gp_optimizer.py:GPOptimizer.__init__`.

Currently, the following error occurs when instancing `GPOptimizer`:
```
...
  File "C:\Users\rp\PycharmProjects\gpcam\gpcam\gp_optimizer.py", line 343, in __init__
    super().__init__(
TypeError: GP.__init__() got an unexpected keyword argument 'sparse_mode'
```

Edit: The same seems to apply to the `normalize_y` kwarg.

**Comment by MarcusMNoack** [comment]
Thank you for bringing this to my attention. This issue has been fixed.
