### ISSUE TITLE
Positional vs keyword argument bug in gpcam/surrogate_model.py

### ISSUE THREAD

**Issue by rfung-uwm-edu** [lbl-camera/gpCAM#35]
In gpcam/surrogate_model.py

lines#150-152 is a call to evaluate_acquisition_function, and lines#170-171 is the definition of evaluate_acquisition_function.

As-is, cost_function in line# 152 is mapped to number_of_maxima_sought in line#170.

To fix this, I suggest specifying all keyword arguments as keyword arguments in the call (lines#150-152), i.e. origin=origin,cost_function=cost_function,cost_function_parameters=cost_function_parameters, instead of relying on their positions in the list of arguments.

Thanks.
Russell Fung (University of Wisconsin Milwaukee)

**Comment by MarcusMNoack** [comment]
HI Russel, I will check this out in the coming days. I'll keep you posted.

**Comment by MarcusMNoack** [comment]
Hi Russel, number_of_maxima_sought was removed from this function definition. Thank you.
