### ISSUE TITLE
Nuisance warning in devo(partial(...)) call

### ISSUE THREAD

**Issue by rfung-uwm-edu** [lbl-camera/gpCAM#37]
In gpcam/surrogate_model.py, lines# 303-305, in the devo(partial(…)) call, if vectorized is True & updating is ‘immediate’, scipy resets updating to ‘deferred’ automatically and displays a warning.

Setting updating ourselves will remove this nuisance warning.

I suggest adding

updating = 'deferred' if vectorized else 'immediate'

before the res = devo(partial(…)) call,and adding updating=updating in the list of input arguments.

Thanks.
Russell Fung (University of Wisconsin Milwaukee)

**Comment by MarcusMNoack** [comment]
Thank you, Russel. I will make these changes available as part of the next update. I will keep you updated here.

**Comment by MarcusMNoack** [comment]
I added this change and it will be part of the next update.
